version: '3'

services:
  mariadb:
    image: mariadb:10.5.4-focal
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - /root/mariadb/data:/var/lib/mysql
    env_file:
      - .env.mariadb

  matomo:
    image: matomo:3.13.6-apache
    restart: always
    depends_on:
      - "mariadb"
    ports:
      - "80:80"
    volumes:
      - /root/matomo/config:/var/www/html/config:rw
      - /root/matomo/logs:/var/www/html/logs
    env_file:
      - .env.matomo
