version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - /root/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  hasura:
    image: hasura/graphql-engine:pull5070-1699dc79
    ports:
      - "80:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - .env.hasura
